

package paypaladdon;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"PayPalExpressCheckoutShortcut",
			"SimpleBannerComponent",
			com.paypal.hybris.addon.jalo.PayPalExpressCheckoutShortcut.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PayPalExpressCheckoutMark",
			"SimpleBannerComponent",
			com.paypal.hybris.addon.jalo.PayPalExpressCheckoutMark.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PayPalCreditShortcut",
			"SimpleBannerComponent",
			com.paypal.hybris.addon.jalo.PayPalCreditShortcut.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PayPalCreditFinancingBanner",
			"SimpleBannerComponent",
			com.paypal.hybris.addon.jalo.PayPalCreditFinancingBanner.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PayPalMiniCartComponent",
			"MiniCartComponent",
			com.paypal.hybris.addon.jalo.PayPalMiniCartComponent.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"PayPalJspIncludeComponent",
			"JspIncludeComponent",
			com.paypal.hybris.addon.jalo.PayPalJspIncludeComponent.class,
			null,
			false,
			null,
			false
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_PayPalExpressCheckoutMark_link();
			
				single_createattr_PayPalMiniCartComponent_payPalExpressCheckoutShortcut();
			
				single_createattr_PayPalMiniCartComponent_payPalCreditShortcut();
			
				single_createattr_PayPalJspIncludeComponent_feature();
			
				single_createattr_PayPalJspIncludeComponent_feature1();
			

	}

	
	public void single_createattr_PayPalExpressCheckoutMark_link() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PayPalExpressCheckoutMark", 
					"link",  
					null,
					"CMSLinkComponent",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PayPalMiniCartComponent_payPalExpressCheckoutShortcut() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PayPalMiniCartComponent", 
					"payPalExpressCheckoutShortcut",  
					null,
					"PayPalExpressCheckoutShortcut",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PayPalMiniCartComponent_payPalCreditShortcut() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PayPalMiniCartComponent", 
					"payPalCreditShortcut",  
					null,
					"PayPalCreditShortcut",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PayPalJspIncludeComponent_feature() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PayPalJspIncludeComponent", 
					"feature",  
					null,
					"SimpleCMSComponent",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_PayPalJspIncludeComponent_feature1() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"PayPalJspIncludeComponent", 
					"feature1",  
					null,
					"SimpleCMSComponent",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PayPalExpressCheckoutShortcut",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PayPalExpressCheckoutMark",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PayPalExpressCheckoutMark_link();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PayPalCreditShortcut",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PayPalCreditFinancingBanner",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PayPalMiniCartComponent",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PayPalMiniCartComponent_payPalExpressCheckoutShortcut();
		
			single_setAttributeProperties_PayPalMiniCartComponent_payPalCreditShortcut();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"PayPalJspIncludeComponent",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_PayPalJspIncludeComponent_feature();
		
			single_setAttributeProperties_PayPalJspIncludeComponent_feature1();
		
	}


		
						public void single_setAttributeProperties_PayPalExpressCheckoutMark_link() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PayPalExpressCheckoutMark", 
								"link",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PayPalMiniCartComponent_payPalExpressCheckoutShortcut() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PayPalMiniCartComponent", 
								"payPalExpressCheckoutShortcut",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PayPalMiniCartComponent_payPalCreditShortcut() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PayPalMiniCartComponent", 
								"payPalCreditShortcut",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PayPalJspIncludeComponent_feature() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PayPalJspIncludeComponent", 
								"feature",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_PayPalJspIncludeComponent_feature1() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"PayPalJspIncludeComponent", 
								"feature1",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
}

	